language: node_js
node_js:
  - "12"
addons:
  chrome: stable
before_install:
  - npm i -g npm@latest
  - npm install -g @angular/cli@8
cache:
  npm: false
script:
  - ng build go-lib && ng test go-lib --watch=false --browsers=ChromeHeadless
