language: node_js
node_js:
  - "10.16.3"
addons:
  chrome: stable
before_install:
  - npm i -g npm@6.9.0
  - npm i -g @angular/cli@9
cache:
  npm: false
script:
  - npm run build_lib && npm run test_lib -- --watch=false
